// <auto-generated />
using System;
using Estacionamento.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Estacionamento.Data.Migrations
{
    [DbContext(typeof(MySqlContext))]
    partial class MySqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Estacionamento.Domain.Entities.RegistroEstacionamentoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHoraEntrada")
                        .HasColumnType("datetime")
                        .HasColumnName("DataHoraEntrada");

                    b.Property<DateTime?>("DataHoraSaida")
                        .HasColumnType("datetime")
                        .HasColumnName("DataHoraSaida");

                    b.Property<int?>("MinutosTotais")
                        .HasColumnType("int")
                        .HasColumnName("MinutosTotais");

                    b.Property<int?>("TabelaDePrecosId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ValorPagar")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("ValorPagar");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("int")
                        .HasColumnName("VeiculoId");

                    b.HasKey("Id");

                    b.HasIndex("TabelaDePrecosId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("RegistroEstacionamento", (string)null);
                });

            modelBuilder.Entity("Estacionamento.Domain.Entities.TabelaDePrecosEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime")
                        .HasColumnName("DataHoraCadastro");

                    b.Property<decimal>("PrecoHora")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("PrecoHora");

                    b.Property<decimal>("PrecoHoraAdicional")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("PrecoHoraAdicional");

                    b.HasKey("Id");

                    b.ToTable("TabelaDePrecos", (string)null);
                });

            modelBuilder.Entity("Estacionamento.Domain.Entities.VeiculoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("Modelo");

                    b.Property<string>("NomeProprietario")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("NomeProprietario");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Placa");

                    b.HasKey("Id");

                    b.ToTable("Veiculo", (string)null);
                });

            modelBuilder.Entity("Estacionamento.Domain.Entities.RegistroEstacionamentoEntity", b =>
                {
                    b.HasOne("Estacionamento.Domain.Entities.TabelaDePrecosEntity", "TabelaDePrecos")
                        .WithMany()
                        .HasForeignKey("TabelaDePrecosId");

                    b.HasOne("Estacionamento.Domain.Entities.VeiculoEntity", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TabelaDePrecos");

                    b.Navigation("Veiculo");
                });
#pragma warning restore 612, 618
        }
    }
}
